### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by woodruffw** [travitch/build-bom#1]
First of all, thanks for the blight shoutout :-)

Feel free to close this; I just wanted to say that this looks really cool! I'm looking forward to seeing how the `ptrace` approach stacks up compared to `LD_PRELOAD` and blight's (relatively dumb) wrapping.

**Comment by travitch** [comment]
Thanks! I'm excited by some aspects of it (e.g., it works with weird build systems that use static binaries, mess with the environment, hard code paths, etc), but it does serialize builds (because every system call stops the central dispatch thread). I'm also interested in incorporating other features that might be useful to other people (e.g., auto AddressSanitizer support or something like that).
